### PR TITLE
add 3.1.0 chinese translation and try to enhance some details in en_us.lang, also try to fix hard-code problem

### PR DESCRIPTION
**Pull request by TUsama**

### CODE REVIEW

**Comment by noobanidus** [comment]
While I appreciate the expansion of the English translation, some of them are only ever presented *within* the context of the spell. Hence why I didn't refer to a few things. 

> roots.modifiers.modifiers.slow_fire.desc=Damaged creatures by wildfire are also slowed.

Slow Fire is only ever accessible through the Wildfire spell. So, when looking at the tooltip of the modifiers, you are specifically within the "Wildfire" spell context. Thus, "Damaged creatures are also slowed" makes sense and is much shorter.

An issue I've had with the length of tooltips is that they sometimes end up stretching off the screen with extremely long descriptions, so I've aimed to keep them succinct and short.

That said, while I appreciate the effort, these aren't the final versions of the descriptions, as it is possible that the names, etc, may change. I'd suggest you wait until I make a commit stating that these are the final versions, etc.

**Comment by TUsama** [comment]
OK，I know that this file will change a lot (maybe) in the future, I translated it because I want to finish it ASAP, considering my study plan, I'll soon be busy in the next few months. It's worth doing some unnecessary work on my free time.

**Comment by noobanidus** [comment]
I'm really sorry for the delays with all of this, I'm planning on trying to finish off the documentation for the next alpha.

**Comment by noobanidus** [comment]
(A lot of what you've already done should still be applicable though, especially for rituals.)

**Pull request closed without merging**
