### PR TITLE
Create ru_RU.lang

### PR DESCRIPTION
**Pull request by bigenergy**

### CODE REVIEW

**Comment by noobanidus** [comment]
Ooh thank you so much! Just so you're aware, the Guide Book can also be translated, but at the current point in time things are a little transitory -- some things may potentially be renamed and other translation strings might be added in the future.

I'm going to merge this but potentially comment again on this in future if I add more keys that need to be translate.

**Comment by GreyMario** [comment]
Looks like the file has some leftover diff markers. Might want to clean those up.

**Comment by noobanidus** [comment]
Thanks, I'll check those out shortly -- I've yet to pull the changes locally.

**Comment by bigenergy** [comment]
@noobanidus You should merge this to 3.0.x.x

**Pull request merged**
