### PR TITLE
Fixed Dev Environment and Optimized Soil Handler

### PR DESCRIPTION
**Pull request by ByThePowerOfScience**
Removed duplicate "instanceof" checks and changed the order of checks so that the handler body only runs if the block is one of the affected elemental soil types.

These irrelevant expensive checks were causing a good bit of lag with the fast harvesting of crops on servers with AgriCraft installed.

### CODE REVIEW

**Comment by ByThePowerOfScience** [comment]
This is intended for the most recent 1.12 branch.  If I chose the wrong target branch, please reassign to the correct one.

**Comment by noobanidus** [comment]
Were you able to get this to compile? I've had a lot of issues getting the dev environment to function so I've been lax on fixing 1.12 issues.

**Comment by ByThePowerOfScience** [comment]
> Were you able to get this to compile? I've had a lot of issues getting the dev environment to function so I've been lax on fixing 1.12 issues.

No, I just edited this file in the browser.

**Comment by ByThePowerOfScience** [comment]
Ok it turns out that, remarkably, I should _test_ my code before submitting it.  Imagine that.

**Comment by ByThePowerOfScience** [comment]
@noobanidus I've shifted over to working on the Roots repo directly, and I'm having trouble understanding your build setup.  Could you explain how you have everything set up?

If you'd like, we can talk more about this via email or Discord instead of here.

**Comment by noobanidus** [comment]
Yeah, it's unfortunately a very complex system. Feel free to drop me a message on Discord -- there should be a link to the Mystic Modding discord in the description/project page.

**Comment by ByThePowerOfScience** [comment]
Development environment is fixed.  I'm going to see if I can't patch some of the other issues I've noticed before this is merged.

**Pull request merged**
