### PR TITLE
Runic soil rework AKA Elemetal Soil

### PR DESCRIPTION
**Pull request by Davoleo**
### Content
- [x] Refactor classes
- [x] Change names
- [x] Reworked textures (by Kalaxi)
- [x] In-world crafting
  - [x] Aeros Soil
  - [x] Aqueous Soil
  - [x] Magmatic Soil
  - [x] Terra Soil (weird name)
- [x] Particles during block transmutation
- [x] Patchouli Documentation
- [x] _Soil particles (to give some kind of mystic effect)_
- [x] JETIF Integration
- [x] Right click to replace classic farmland with elemental soil without having to remove the crops (does this really have a use? 🤔 )

### CODE REVIEW

**Comment by duely** [comment]
` Right click to replace classic farmland with elemental soil without having to remove the crops (does this really have a use? 🤔 )` it was specifically requested -- the fact that base runic soil has a growth boost makes it worthwhile to change but it's slightly painful.

**Comment by Davoleo** [comment]
Oh ok, didn't know it has a growth boost

**Comment by duely** [comment]
Yeah that was something new I added a while ago that Squid was talking about but hadn't been able to implement

**Comment by Davoleo** [comment]
I'll do the last tweaks on particles directly in the master branch, this is basically complete

**Pull request merged**
