### PR TITLE
add Chinese ttranslation + change a code detail

### PR DESCRIPTION
**Pull request by TUsama**
Not that easy, but finally I have finished  it
I don't know why my last or key show up again, seems that their keys are different.
I change a code detail in fc33c06, I wonder if it can work because I am not a programmer lol.

### CODE REVIEW

**Comment by Blueberryy** [comment]
T-thank you for ttranslation!

**Comment by noobanidus** [comment]
Thank you very much! I really appreciate the effort that you have put into this.

I would like to apologise as the 3.1.0 branch of Roots is going to have new documentation. The spell interface and the spell modifier system are not yet written. Additionally, there are potentially changes to other parts of the document. As such, there are a number of entries that have just been removed until I have the time to write them again.

So, I am very sorry. I **can** merge your pull request to use it, but the documentation will be changing over the next few weeks. If you would rather I waited for another pull request, this can be done. 

Otherwise, I can merge it in now, and then If you want to, you can start a new branch and edit/add files as necessary.

**Comment by TUsama** [comment]
got it. but It seems that the new patchouli book doesn't work yet. Anyway, I'll keep following your progress.

**Comment by TUsama** [comment]
and the code error has been fixed in c84862f

**Pull request closed without merging**
